defaults: &defaults
  adapter: postgresql
  username: postgres
  password: postgres
  host: localhost
  port: 5432
  pool: 10
  timeout: 5000

development:
  database: question_answer_dev
  <<: *defaults

test:
  database: question_answer_test
  <<: *defaults

production:
  database: question_answer_production
  <<: *defaults
